# Generated by Django 6.0 on 2025-12-23 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("graflow", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="cacheentry",
            name="cacheentry_namespace_key_uniq",
        ),
        migrations.RemoveConstraint(
            model_name="checkpoint",
            name="checkpoint_thread_ns_id_uniq",
        ),
        migrations.RemoveConstraint(
            model_name="checkpointblob",
            name="checkpointblob_thread_ns_channel_version_uniq",
        ),
        migrations.RemoveConstraint(
            model_name="checkpointwrite",
            name="checkpointwrite_thread_ns_id_task_idx_uniq",
        ),
        migrations.RemoveConstraint(
            model_name="store",
            name="store_prefix_key_uniq",
        ),
        migrations.RenameIndex(
            model_name="flow",
            new_name="graflow_flo_user_id_d7fe91_idx",
            old_name="graflow_flow_user_app_name_flow_type_idx",
        ),
        migrations.AlterUniqueTogether(
            name="cacheentry",
            unique_together={("namespace", "key")},
        ),
        migrations.AlterUniqueTogether(
            name="checkpoint",
            unique_together={("thread_id", "checkpoint_ns", "checkpoint_id")},
        ),
        migrations.AlterUniqueTogether(
            name="checkpointblob",
            unique_together={("thread_id", "checkpoint_ns", "channel", "version")},
        ),
        migrations.AlterUniqueTogether(
            name="checkpointwrite",
            unique_together={("thread_id", "checkpoint_ns", "checkpoint_id", "task_id", "idx")},
        ),
        migrations.AlterUniqueTogether(
            name="store",
            unique_together={("prefix", "key")},
        ),
    ]
