# Generated by Django 6.0 on 2025-12-23 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("graflow", "0002_remove_cacheentry_cacheentry_namespace_key_uniq_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FlowType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "app_name",
                    models.CharField(db_index=True, help_text="Application name", max_length=255),
                ),
                (
                    "flow_type",
                    models.CharField(
                        db_index=True,
                        help_text="Type of the flow (e.g., 'hello_world')",
                        max_length=255,
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        help_text="Version string (e.g., 'v1', '1.0.0', 'beta')", max_length=50
                    ),
                ),
                (
                    "builder_path",
                    models.CharField(
                        help_text="Path to builder function (e.g., 'myapp.graphs:build_graph')",
                        max_length=500,
                    ),
                ),
                (
                    "state_path",
                    models.CharField(
                        help_text="Path to state class (e.g., 'myapp.graphs:GraphState')",
                        max_length=500,
                    ),
                ),
                (
                    "is_latest",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Whether this is the latest version of this flow type",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether this flow type is active and can be used",
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        blank=True,
                        help_text="Human-readable name for this flow type",
                        max_length=255,
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Description of this flow type"),
                ),
                (
                    "crud_permission_class",
                    models.CharField(
                        default="rest_framework.permissions.IsAuthenticated",
                        help_text=(
                            "Permission class path for CRUD operations "
                            "(e.g., 'myapp.permissions:CustomPermission')"
                        ),
                        max_length=500,
                    ),
                ),
                (
                    "resume_permission_class",
                    models.CharField(
                        default="rest_framework.permissions.IsAuthenticated",
                        help_text=(
                            "Permission class path for resume operations "
                            "(e.g., 'myapp.permissions:CustomPermission')"
                        ),
                        max_length=500,
                    ),
                ),
                (
                    "crud_throttle_class",
                    models.CharField(
                        blank=True,
                        help_text=(
                            "Throttle class path for CRUD operations "
                            "(e.g., 'myapp.throttling:PremiumThrottle'). "
                            "Optional - uses default viewset throttling if blank."
                        ),
                        max_length=500,
                    ),
                ),
                (
                    "resume_throttle_class",
                    models.CharField(
                        blank=True,
                        help_text=(
                            "Throttle class path for resume operations "
                            "(e.g., 'myapp.throttling:BasicThrottle'). "
                            "Optional - uses default viewset throttling if blank."
                        ),
                        max_length=500,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "graflow_flow_type",
                "indexes": [
                    models.Index(
                        fields=["app_name", "flow_type", "is_latest", "is_active"],
                        name="graflow_flowtype_latest_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_latest", True)),
                        fields=("app_name", "flow_type"),
                        name="graflow_flowtype_one_latest_per_app_type",
                    )
                ],
                "unique_together": {("app_name", "flow_type", "version")},
            },
        ),
    ]
